# Generated by Django 4.1.4 on 2022-12-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('deskripsi', models.CharField(blank=True, max_length=100, null=True)),
                ('pencipta', models.CharField(blank=True, max_length=100, null=True)),
                ('harga', models.CharField(blank=True, max_length=100, null=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karya.kategori')),
            ],
            options={
                'verbose_name_plural': 'Artikel',
            },
        ),
    ]
